version: '3'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    restart: always
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80